sonar.projectKey=hrms
sonar.projectName=HRMS
sonar.branch.name=dev
sonar.host.url=https://sonar.equest.solutions
sonar.token=${env.SONAR_TOKEN}

sonar.modules=frontend-hrms,backend-hrms

frontend-hrms.sonar.projectName=HRMS Frontend
frontend-hrms.sonar.sources=src
frontend-hrms.sonar.language=js

backend-hrms.sonar.projectName=HRMS Backend
backend-hrms.sonar.sources=.
backend-hrms.sonar.language=js